### ISSUE TITLE
findInSowpodsMap Function is not written properly. 

### ISSUE THREAD

**Issue by manishengi** [anubhavchaturvedi/PayPal-training#13]

**Comment by fhalde** [comment]
what error are you getting? can you specify?

**Comment by manishengi** [comment]
I am not getting errors.But the function is not written properly. Check its return statement.

**Comment by manishengi** [comment]
Functionality wise function is giving correct answers. But it return in donkey style

**Comment by RamprasadMurugesan** [comment]
we are looking at it

**Comment by ashajyothi-iitbhu** [comment]
vector<string> a;
        return a;

What is this 'a' ?

**Comment by fhalde** [comment]
we need to return a non null vector. so dummy vector thats it. If we return null the for loop might segfault

**Comment by fhalde** [comment]
@RamprasadMurugesan  you working on it right? once committed close the issue

**Comment by ashajyothi-iitbhu** [comment]
return vector<string>();

**Comment by ashajyothi-iitbhu** [comment]
return vector<string>(); is the correct one then.

**Comment by ashajyothi-iitbhu** [comment]
Sorry..
return vector<string>();
