### ISSUE TITLE
Make two functions addConstraint and removeConstraint

### ISSUE THREAD

**Issue by anubhavchaturvedi** [anubhavchaturvedi/PayPal-training#14]
In addConstraint we will add characters present in the constraint to the rack Similarly delete the characters at removeConstraint.

**Comment by anubhavchaturvedi** [comment]
@7coder7 , @ashajyothi-iitbhu , @RamprasadMurugesan : continue the discussion here and close it when done with the commit id given in the closing comment

**Comment by fhalde** [comment]
its implemeted as addConstraintToRack(string) and removeConstraintFromRack(string)

**Comment by fhalde** [comment]
closed #14
