### ISSUE TITLE
Rename findInSowpodsMap to getAnagramListFromSowpodsMap

### ISSUE THREAD

**Issue by anubhavchaturvedi** [anubhavchaturvedi/PayPal-training#16]

**Comment by anubhavchaturvedi** [comment]
I am taking it up

**Comment by fhalde** [comment]
make sure to refactor as well @anubhavchaturvedi

**Comment by manishengi** [comment]
vector<string> findInSowpodsMap(string key) {
        vector<string> x;
        if( sowpods.find(key) != sowpods.end() ) {
            x = sowpods.find( key )->second;
        }

```
    return x;
}
```

this look much better to me

**Comment by manishengi** [comment]
shikha here :P

**Comment by anubhavchaturvedi** [comment]
completed - commit d4a2a18fe21ec80c9d38e2db6da6f948949e7665
