### ISSUE TITLE
Can we merge both the add and remove constraints to one single function?

### ISSUE THREAD

**Issue by ashajyothi-iitbhu** [anubhavchaturvedi/PayPal-training#17]

**Comment by ashajyothi-iitbhu** [comment]
@7coder7  @RamprasadMurugesan  
The function definitions are pretty much the same,. right!

**Comment by RamprasadMurugesan** [comment]
yeah no issues

**Comment by fhalde** [comment]
yes but separating them out seems a better option.

**Comment by ashajyothi-iitbhu** [comment]
Other teams, suggstion please!

**Comment by anubhavchaturvedi** [comment]
Created the issue to resolve this - issue #19

**Comment by fhalde** [comment]
@padmaja20nov do you need two function for add and remove or one function that'll do task based on some parameter?

**Comment by ashajyothi-iitbhu** [comment]
@VidyashreeBL @Rubeenaks

**Comment by ashajyothi-iitbhu** [comment]
Ohkk..
Closed!
