### ISSUE TITLE
Call the generateBlankReplacedPowerSet() inside the generatePowerSetOfRack() itself

### ISSUE THREAD

**Issue by padmaja20nov** [anubhavchaturvedi/PayPal-training#21]

**Comment by fhalde** [comment]
@padmaja20nov  isnt it good that way? when someone will walk through the code, he might not go into the function definition. so keeping generateBlankReplacedPowerSet(powerSet, POWERSET_RACKS); inside that function will hide away the fact that this was ever called. got it? :dancer:

**Comment by padmaja20nov** [comment]
But when we say generate the powerset, we mean with or without blanks...

**Comment by fhalde** [comment]
without blanks

**Comment by anubhavchaturvedi** [comment]
They need to be separate because one of them is recursive and the other is not

**Comment by anubhavchaturvedi** [comment]
Sorry. My mistake, yes this can be done and should be done.

**Comment by anubhavchaturvedi** [comment]
The one reason I think they must be separate is ease of testing. It will be easier to point out which of the two are going wrong if we have to.

**Comment by fhalde** [comment]
exactly. so what have we decided?

**Comment by anubhavchaturvedi** [comment]
Leave them as it is.
