### ISSUE TITLE
replaceBlankTile is written twice with different parameters, can be merged?

### ISSUE THREAD

**Issue by RamprasadMurugesan** [anubhavchaturvedi/PayPal-training#23]

**Comment by ashajyothi-iitbhu** [comment]
Yeah.. One with two parameters, and one with three. 

We should combine them both.

**Comment by ashajyothi-iitbhu** [comment]
@7coder7 @anubhavchaturvedi

**Comment by anubhavchaturvedi** [comment]
The one with 3 parameters is a recursive function and the other is not
