### ISSUE TITLE
Test Environment setup issue

### ISSUE THREAD

**Issue by manishengi** [anubhavchaturvedi/PayPal-training#26]

**Comment by fhalde** [comment]
do we have to perform unit testing for our part of the code? or for the whole project some team is doing it?

**Comment by shikha151** [comment]
Ideally people have to write test cases for their own code. If anyone knows anything about unit testing in C++ or finds out anything that works please do tell.

**Comment by manishengi** [comment]
http://wiki.codeblocks.org/index.php?title=UnitTesting

Use this Link to start with Codeblock Unit Testing

**Comment by manishengi** [comment]
closed..
commit c8752fa48ecea813b33470582949e059d2baac79
