### ISSUE TITLE
ScrabbleWords.cpp not implemented

### ISSUE THREAD

**Issue by anubhavchaturvedi** [anubhavchaturvedi/PayPal-training#30]
ScrabbleWords.cpp
PUBLIC API :

ScrabbleWords(string filename)
    filepath - accepts the path to the list of words file(sowpods).
    Responsible for creating internal structure that stores sowpods ( the official scrabble dictionary ).
vector<string> getAnagrams(string letters)
    letters- The letters whose anagrams have to be searched for
    Returns all the anagrams of the given letters
bool isWordValid(string word)
    word - The word to be searched
Check if the word is present in the given file.

PRIVATE API :

string getSortedString(string str)
    str - The string whose letters need to be sorted
Returns a sorted string str.
void insertInSowpodsMap(string word)
    word- the value to be added to the internal structure of sowpods
Inserts a new entry into the sowpod map.

**Comment by fhalde** [comment]
@anubhavchaturvedi done
