### ISSUE TITLE
How to include functions from other classes into my class

### ISSUE THREAD

**Issue by shikha151** [anubhavchaturvedi/PayPal-training#35]
I have to use getSortedString(rack), getCharScore(ch) and value of some constants from other classes to complete the functionality of my class. Anyone who knows how to do this please do tell.

**Comment by anubhavchaturvedi** [comment]
I will create a Util.cpp and Util.h file and there these functions will be available
You can access it from there. The definition will remain same

**Comment by manishengi** [comment]
You have to include ScrabbleWordScore.h into your header file.

**Comment by shikha151** [comment]
I also need the value of the constant EMPTY_TILE.
