### ISSUE TITLE
Code compilation error due to C++11 not being used by IDE

### ISSUE THREAD

**Issue by anubhavchaturvedi** [anubhavchaturvedi/PayPal-training#5]

**Comment by anubhavchaturvedi** [comment]
Hi the issue is because the the IDE is using C++98 to compile it

To change it in CodeBlocks, go to settings -> compiler
tick C++11 ISO for compilation in the checkboxes

**Comment by anubhavchaturvedi** [comment]
![image](https://cloud.githubusercontent.com/assets/3113465/8869128/f53be302-31fd-11e5-9c50-e96c3a538f65.png)

**Comment by Rubeenaks** [comment]
http://stackoverflow.com/questions/16951376/how-to-change-mode-from-c98-mode-in-dev-c-to-a-mode-that-supports-c0x-ran

In case anyone is using dev c++

**Comment by fhalde** [comment]
dev c++ ppl can add -std=c++0x in the compiler options
