### ISSUE TITLE
Readme File

### ISSUE THREAD

**Issue by Rubeenaks** [anubhavchaturvedi/PayPal-training#7]
I have created a readme file .Everyone write your problem statement there.

**Comment by Rubeenaks** [comment]
Anubhav why dont you have a readme defining the general problem statement?

**Comment by ashajyothi-iitbhu** [comment]
Team 1 
Given a set of characters on the rack for the first move in Scrabble game, find the words of length greater than 1 from the dictionary, that can be formed out of them.
And then suggest the words corresponding to the top 5 scores.

**Comment by Rubeenaks** [comment]
put it in readme

**Comment by anubhavchaturvedi** [comment]
done - commit 3566398
