### ISSUE TITLE
Does the anagram map have words which are not anagram as well?

### ISSUE THREAD

**Issue by anubhavchaturvedi** [anubhavchaturvedi/PayPal-training#8]

**Comment by anubhavchaturvedi** [comment]
No the changes for that have to be made by team one
Allocating to Manish

**Comment by manishengi** [comment]
Anubhav, This issue has to be solved by  team one.
I am from team 2..
We are handling the blank character issue....

**Comment by anubhavchaturvedi** [comment]
@7coder7  make sure you close the issue by mentioning 'commit <commit-id>' in the comment

**Comment by fhalde** [comment]
yes it has the word in the vector list.

**Comment by 7coder7** [comment]
commit

**Comment by 7coder7** [comment]
'commit'
